// Generated by CoffeeScript 1.6.3
var Code, model, mongoose;

mongoose = require('mongoose');

model = require("./model.js");

Code = model.Code;

exports.index = function(req, res) {
  return res.render('index', {
    title: 'paircodr'
  });
};

exports["new"] = function(req, res) {
  var code;
  code = new Code;
  return code.save(function(err) {
    return res.redirect("/" + code._id);
  });
};

exports.code = function(req, res) {
  return Code.findById(req.params.id, function(err, code) {
    console.log(!code);
    if (err || !code) {
      return res.redirect("/");
    }
    return res.render("code/index", {
      title: code.title,
      code: code
    });
  });
};
